"use strict";
var express = require("express");
var router = express.Router();
var auth = require("../middlewares/auth");
var createAdmin = require("../controllers/Admin/createAdmin");
var deleteAdmin = require("../controllers/Admin/deleteAdmin");
router.use(auth);
router.post("/add", createAdmin);
router.delete("/delete", deleteAdmin);
module.exports = router;
